In [1]:
import numpy as np

In [2]:
import pandas as pd

In [3]:
arr = np.array([1,2,3,4,5])

In [4]:
type(arr)

numpy.ndarray

In [5]:
arr.shape

(5,)

In [6]:
arr.ndim

1

In [7]:
arr2 = np.array([[1,2,3],[4,5,6]])

In [8]:
arr2.shape

(2, 3)

In [9]:
arr2.ndim

2

In [10]:
np.zeros((5,5,5))

array([[[0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0.]],

       [[0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0.]],

       [[0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0.]],

       [[0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0.]],

       [[0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0.]]])

In [11]:
np.ones((3,3))

array([[1., 1., 1.],
       [1., 1., 1.],
       [1., 1., 1.]])

In [17]:
np.random.randint(1,10,(4,4))

array([[1, 2, 6, 8],
       [1, 2, 7, 4],
       [3, 8, 9, 9],
       [7, 5, 4, 9]])

In [16]:
help(np.random.randint)

Help on built-in function randint:

randint(...) method of mtrand.RandomState instance
    randint(low, high=None, size=None, dtype='l')
    
    Return random integers from `low` (inclusive) to `high` (exclusive).
    
    Return random integers from the "discrete uniform" distribution of
    the specified dtype in the "half-open" interval [`low`, `high`). If
    `high` is None (the default), then results are from [0, `low`).
    
    Parameters
    ----------
    low : int
        Lowest (signed) integer to be drawn from the distribution (unless
        ``high=None``, in which case this parameter is one above the
        *highest* such integer).
    high : int, optional
        If provided, one above the largest (signed) integer to be drawn
        from the distribution (see above for behavior if ``high=None``).
    size : int or tuple of ints, optional
        Output shape.  If the given shape is, e.g., ``(m, n, k)``, then
        ``m * n * k`` samples are drawn.  Default is None, i

In [18]:
data = np.random.randint(1,10,(4,4))

In [20]:
data.reshape(8,2)

array([[1, 1],
       [6, 5],
       [9, 8],
       [3, 6],
       [4, 8],
       [7, 5],
       [7, 7],
       [8, 1]])

In [21]:
data.reshape(-1,8)

array([[1, 1, 6, 5, 9, 8, 3, 6],
       [4, 8, 7, 5, 7, 7, 8, 1]])

In [23]:
data.reshape(-1,1).shape

(16, 1)

In [27]:
data.reshape(1,-1).ndim

2

In [28]:
data

array([[1, 1, 6, 5],
       [9, 8, 3, 6],
       [4, 8, 7, 5],
       [7, 7, 8, 1]])

In [31]:
data[1:3,2:4]

array([[3, 6],
       [7, 5]])

In [33]:
data[:,2:4]

array([[6, 5],
       [3, 6],
       [7, 5],
       [8, 1]])

In [34]:
data

array([[1, 1, 6, 5],
       [9, 8, 3, 6],
       [4, 8, 7, 5],
       [7, 7, 8, 1]])

### Operations

In [35]:
np.max(data)

9

In [36]:
np.max(data, axis=1)

array([6, 9, 8, 8])

In [37]:
np.max(data, axis=0)

array([9, 8, 8, 6])

In [38]:
np.sort(data,axis=1)

array([[1, 1, 5, 6],
       [3, 6, 8, 9],
       [4, 5, 7, 8],
       [1, 7, 7, 8]])

In [39]:
np.sort(data,axis=0)

array([[1, 1, 3, 1],
       [4, 7, 6, 5],
       [7, 8, 7, 5],
       [9, 8, 8, 6]])

In [40]:
np.sort(data)

array([[1, 1, 5, 6],
       [3, 6, 8, 9],
       [4, 5, 7, 8],
       [1, 7, 7, 8]])

In [41]:
np.log10(data)

array([[0.        , 0.        , 0.77815125, 0.69897   ],
       [0.95424251, 0.90308999, 0.47712125, 0.77815125],
       [0.60205999, 0.90308999, 0.84509804, 0.69897   ],
       [0.84509804, 0.84509804, 0.90308999, 0.        ]])

In [42]:
np.matmul(data,data)

array([[ 69,  92,  91,  46],
       [135, 139, 147, 114],
       [139, 159, 137, 108],
       [109, 134, 127, 118]])

In [43]:
np.linalg.inv(data)

array([[ 0.05470588,  0.12      , -0.22      ,  0.10647059],
       [-0.18      , -0.04      ,  0.24      , -0.06      ],
       [ 0.09588235, -0.08      , -0.02      ,  0.10058824],
       [ 0.11      ,  0.08      ,  0.02      , -0.13      ]])

In [45]:
data + 5

array([[ 6,  6, 11, 10],
       [14, 13,  8, 11],
       [ 9, 13, 12, 10],
       [12, 12, 13,  6]])

In [46]:
data + data

array([[ 2,  2, 12, 10],
       [18, 16,  6, 12],
       [ 8, 16, 14, 10],
       [14, 14, 16,  2]])

In [47]:
data = np.array([1,2,0,0,4,0])

In [49]:
ind = np.where(data > 0)

In [50]:
data[ind]

array([1, 2, 4])

In [51]:
ind

(array([0, 1, 4]),)

In [60]:
data = np.random.randint(1,10,(3,3,3))

In [68]:
np.sum(data,axis=1)

array([[19, 22, 17],
       [17, 16,  9],
       [23, 15, 18]])

In [63]:
#np.sum(data,axis=3)

In [64]:
data

array([[[6, 8, 7],
        [8, 9, 4],
        [5, 5, 6]],

       [[3, 5, 1],
        [8, 8, 4],
        [6, 3, 4]],

       [[9, 5, 5],
        [5, 8, 6],
        [9, 2, 7]]])

In [75]:
data = np.random.randint(0,10,(16,16))

In [72]:
res = np.zeros((4,4))

In [82]:
res[0,0] = np.sum(data[:4,0:4])

In [83]:
res[0,1] = np.sum(data[:4,4:8])

In [84]:
res[0,2] = np.sum(data[:4,8:12])
res[0,3] = np.sum(data[:4,12:16])

In [85]:
res[1,0] = np.sum(data[4:8,:4])

In [86]:
res

array([[63., 77., 81.,  0.],
       [67.,  0.,  0.,  0.],
       [ 0.,  0.,  0.,  0.],
       [ 0.,  0.,  0.,  0.]])

In [87]:
for i in range(4):
    for j in range(4):
        res[i,j] = np.sum(data[ i*4: i*4+4, j*4: j*4+4])

In [88]:
res

array([[63., 77., 81., 86.],
       [67., 60., 66., 78.],
       [78., 72., 56., 66.],
       [62., 76., 81., 70.]])

In [97]:
res = np.vsplit(data,[4,8,12])

In [113]:
result = []
for e in res:
    result.extend(np.hsplit(e,[4,8,12]))

In [114]:
final = []
for r in result:
    final.append(np.sum(r))

In [120]:
np.array(final).reshape(4,4)

array([[63, 77, 81, 86],
       [67, 60, 66, 78],
       [78, 72, 56, 66],
       [62, 76, 81, 70]])

In [ ]:
np.hstack